### ISSUE TITLE
no _init_.py file.

### ISSUE THREAD

**Issue by mcgeo52** [gregmccoy/sproutvideo-python#1]
I have attempted to install the Python module. The results were:
```
[ec2-user@ip-172-31-1-228 ~]$ sudo python setup.py install
running install
running build
running build_py
package init file 'sprout/__init__.py' not found (or not a regular file)
package init file 'sprout/__init__.py' not found (or not a regular file)
running install_lib
creating /usr/local/lib/python2.7/site-packages/sprout
copying build/lib/sprout/video.py -> /usr/local/lib/python2.7/site-packages/sprout
copying build/lib/sprout/tag.py -> /usr/local/lib/python2.7/site-packages/sprout
copying build/lib/sprout/client.py -> /usr/local/lib/python2.7/site-packages/sprout
byte-compiling /usr/local/lib/python2.7/site-packages/sprout/video.py to video.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/sprout/tag.py to tag.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/sprout/client.py to client.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/site-packages/sproutvideo_python-0.1.egg-info

```
I was concerned about the error messages regarding the init file, but decided to proceed since the files appeared to be in the site-packages folder.

However, the result was:
```
Traceback (most recent call last):
  File "sprout-upload-test.py", line 2, in <module>
    import sprout
ImportError: No module named sprout
```

The sprout folder is there, but not being found. I suspect this is because of the missing init file.

I have tried adding an empty _init_.py file to the sprout folder and running the install again.  I get the error message when running install, but the _init_.py file shows up in the sprout folder in the site-packages folder along with an _init_.pyc file. However, I still get the "No module named sprout" error.

I used underscores before and after init in th file name, but this program changes them to delimiters for italics.

**Comment by gregmccoy** [comment]
@mcgeo52 What version of python are you running? You probably won't run into this issue for Python 3.3 and higher.

**Comment by mcgeo52** [comment]
Moving to 3.6 solved this issue.

Thank you.
